### ISSUE TITLE
Duplicated indicator

### ISSUE THREAD

**Issue by balazser** [rexebin/classio#2]
If a method is implemented through multiple interfaces then the indicator text appears multiple times.

![image](https://user-images.githubusercontent.com/20303564/42625646-954cf4fa-85c8-11e8-9d7e-14cff317106e.png)

**Comment by rexebin** [comment]
Thank you for report. I will put a fix up.

**Comment by balazser** [comment]
thank you!

**Comment by rexebin** [comment]
fixed with 0.3.4.
